### ISSUE TITLE
Ripple delete is affecting another channel too

### ISSUE THREAD

**Issue by tin2tin** [snuq/VSEQF#1]
When ripple deleting a strip in channel 1 the strip above in channel 2 moves up into channel 3 and the rest of the strips in channel 2 is rippled to the left. The strips in channel 2 should be untouched when ripple deleting a strip in channel 1. 

Watch this gif for more explanation:
https://devtalk.blender.org/uploads/default/original/2X/5/589478b28d481eb8860dffb2422fd845f584100a.gif

**Comment by snuq** [comment]
This is currently intended behavior, any strip that continues after the end of the ripple-deleted strip may be in sync with other strips after it, and must be moved along with them.
You did make me realize however, that the ripple delete is somewhat broken, and I did some reworking on it to make it properly handle overlapping multiple strips...
Also, im giving this some thought, and posted in the blender chat asking for other opinions on ripple cases.
