### ISSUE TITLE
Restore menus after unregistering

### ISSUE THREAD

**Issue by tin2tin** [snuq/VSEQF#11]
If you add these two lines to unregistering, the original menus will be restored:
`
bpy.ops.script.python_file_run(filepath= bpy.utils.resource_path(type="LOCAL")+"\\scripts\\startup\\bl_ui\\space_sequencer.py")
bpy.ops.script.reload()
`

**Comment by tin2tin** [comment]
On 2.92 this is causing a context error...

**Comment by snuq** [comment]
Tried it out, but yeah, seeing an error too when I try this... not sure what to do about it since it involves a python file that is part of Blender itself.  Id suggest just restarting blender after disabling, as I dont want to cause an error.
