### ISSUE TITLE
Uninstalling VSEQF leaves menus broken.

### ISSUE THREAD

**Issue by tin2tin** [snuq/VSEQF#13]
This is all there is left of the VSE menus anter a removal of VSEQF, making the VSE unuseable:
![image](https://user-images.githubusercontent.com/1322593/128155925-f43846df-5283-44a0-bd32-cbb1bc6f1cad.png)

I think you should try to figure out how to execute space_sequencer.py as part of the uninstallation process to restore the original vse menus.

**Comment by snuq** [comment]
i dont know of any way to fix this... its a limitation of the way blender handles the menus, and its not really a priority for me since restarting after an uninstall isnt a big deal.
