### ISSUE TITLE
Error clicking in editing window

### ISSUE THREAD

**Issue by knoxfighter** [snuq/VSEQF#14]
I installed the plugin and everytime i try to click into the Sequencer this error occurs:

```
Traceback (most recent call last):
  File "C:\Users\Philipp\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\VSEQF-2_82_2\grabs.py", line 322, in invoke
    self.click_mode = context.window_manager.keyconfigs.active.preferences.select_mouse
AttributeError: 'NoneType' object has no attribute 'select_mouse'

location: <unknown location>:-1
```

Makes this plugin unusable. Since that code is not changed for 2 years now, i suspect i have something wrongly setup.

Something i found from quick googling: https://developer.blender.org/T59064

**Comment by snuq** [comment]
hmm, that is a rather unfortunate bug in blender I was not aware of... it does seem like the only 'solution' is just to default to a specific mode of operation if that setting is not found.  I have implement a check on that, but I dont know how to backport that to the 2.82 version of the script that you are using, and I really cant provide support for older versions of blender.

you can edit the grabs.py file if you dont mind getting your hands dirty a bit, just change line 322 and line 738 into this:
```
    try:
        self.click_mode = context.window_manager.keyconfigs.active.preferences.select_mouse
    except:
        self.click_mode = 'LEFT'
```

**Comment by knoxfighter** [comment]
Thank you for the quick answer and the workaround.
I didn't expect you to fix it for older versions :)
I will use that workaround now.
