### ISSUE TITLE
Lots of Menus and Keymaps not Found

### ISSUE THREAD

**Issue by LorenzWieseke** [snuq/VSEQF#15]
arning: 'Scene_Tools_PT_sel_sim' doesn't have upper case alpha-numeric prefix      
register_class(...):
Warning: 'Scene_Tools_PT_scene_tools' doesn't have upper case alpha-numeric prefix  
register_class(...):
Warning: 'tot.mainmen_col' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'tot.mainmen_colversion' does not contain '_PT_' with prefix and suffix    
register_class(...):
Warning: 'tot.mainmen_3d' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'SceneBenchmark_Menu_TOT' does not contain '_PT_' with prefix and suffix   
register_class(...):
Warning: 'MaterialBenchmark_Menu_TOT' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'ImageResizer_Menu_TOT' does not contain '_PT_' with prefix and suffix     
register_class(...):
Warning: 'tot.findin' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'tot.actionsin' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'TOT_MatB_UL_items' doesn't have upper case alpha-numeric prefix
register_class(...):
Warning: 'TOT_ImageResizer_UL_items' doesn't have upper case alpha-numeric prefix   
Bypassing debug mode
Warning: property 'direction' not found in keymap item 'OperatorProperties'
Warning: property 'direction' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'ripple' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'ripple' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'ripple' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'ripple' not found in keymap item 'OperatorProperties'
Warning: property 'use_unselected' not found in keymap item 'OperatorProperties'
Warning: property 'use_unselected' not found in keymap item 'OperatorProperties'
Warning: property 'speed_factor' not found in keymap item 'OperatorProperties'
Warning: property 'speed_factor' not found in keymap item 'OperatorProperties'
Warning: property 'speed_factor' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'preset' not found in keymap item 'OperatorProperties'
Warning: property 'speed' not found in keymap item 'OperatorProperties'
Warning: property 'speed' not found in keymap item 'OperatorProperties'
Warning: property 'speed' not found in keymap item 'OperatorProperties'
Warning: property 'speed' not found in keymap item 'OperatorProperties'
Warning: property 'speed' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'gap_remove' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'gap_remove' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'gap_remove' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'gap_remove' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'gap_remove' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'gap_remove' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'gap_remove' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'select_mode' not found in keymap item 'OperatorProperties'
Warning: property 'keep_audio' not found in keymap item 'OperatorProperties'
Warning: property 'type' not found in keymap item 'OperatorProperties'
Warning: property 'type' not found in keymap item 'OperatorProperties'
Warning: property 'type' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'side' not found in keymap item 'OperatorProperties'
Warning: property 'is_removing_transitions' not found in keymap item 'OperatorProperties'
Warning: property 'is_removing_transitions' not found in keymap item 'OperatorProperties'
Warning: property 'delete_selection' not found in keymap item 'OperatorProperties'
Warning: property 'delete_selection' not found in keymap item 'OperatorProperties'
Warning: property 'concatenate_all' not found in keymap item 'OperatorProperties'
Warning: property 'is_towards_left' not found in keymap item 'OperatorProperties'
Warning: property 'concatenate_all' not found in keymap item 'OperatorProperties'
Warning: property 'is_towards_left' not found in keymap item 'OperatorProperties'
Warning: property 'concatenate_all' not found in keymap item 'OperatorProperties'
Warning: property 'is_towards_left' not found in keymap item 'OperatorProperties'
Warning: property 'concatenate_all' not found in keymap item 'OperatorProperties'
Warning: property 'is_towards_left' not found in keymap item 'OperatorProperties'
Warning: property 'direction' not found in keymap item 'OperatorProperties'
Warning: property 'trim_target_channel' not found in keymap item 'OperatorProperties'
Warning: property 'direction' not found in keymap item 'OperatorProperties'
Warning: property 'trim_target_channel' not found in keymap item 'OperatorProperties'
Warning: property 'direction' not found in keymap item 'OperatorProperties'
Warning: property 'trim_target_channel' not found in keymap item 'OperatorProperties'
Warning: property 'direction' not found in keymap item 'OperatorProperties'
Warning: property 'trim_target_channel' not found in keymap item 'OperatorProperties'

**Comment by snuq** [comment]
Without additional information, I cant classify this as a bug, nor do I know where to begin to look, closing this for now, feel free to let me know, or post another bug if you encounter this again.
