### ISSUE TITLE
3.x Support?

### ISSUE THREAD

**Issue by asbestosbill** [snuq/VSEQF#17]
Hey, this looks amazing. I was just wondering if you plan on developing it for Blender 3.x. It seems to give a lot of add-on developers trouble, but I would appreciate it. I donated a bit to help you out. Cheers.

**Comment by snuq** [comment]
Did some testing, only a bit of an issue with blender enforcing integer variables, that broke the import, 3point, and zooms.  Made an update that hopefully will fix all those, try out the master version and see if you have any problems.
Still one bug - the vu meter doesnt update on playback, not sure whats going on there yet...

**Comment by snuq** [comment]
With a bit of help from [pKrime](https://github.com/pKrime), the bugs in blender 3 should be ironed out.  Let me know if I missed anything
