### ISSUE TITLE
Conflicts with new 4.0 Retiming Keys and keyboard problem

### ISSUE THREAD

**Issue by MumuMundo** [snuq/VSEQF#26]
Hello & thanks for all you've done! It's my first time using the addon, and these are some issues I spotted in the 4.0 version.

https://github.com/snuq/VSEQF/assets/152472795/9c0ae361-b858-4380-8326-e3a6d6863f77

**Comment by snuq** [comment]
So thats essentially a new editing mode in the sequencer, I found how to detect that its active and I can disable certain features while that is the case (context menus, grab functionality, delete functionality), so blender will fall back to default behavior.

Also the shortcut not working after clicking is issue #16.  The default Tweak tool is eating inputs somehow while in left-click mode only.  Switching that to 'Select Box' mode for the tool will fix the problem (or use right click to select mode), but I'm still working on a more permanent fix.
