### ISSUE TITLE
Frame Change Handler Err

### ISSUE THREAD

**Issue by TestPilot02** [snuq/VSEQF#30]
I'm seeing this Err in my console during baking a cloth+ rigid body simulation. I believe it is because I do not have the VSE open on screen. I'm guessing this just needs an exception pass added in for the cases where the user isn't actively using the VSE. 

Error in bpy.app.handlers.frame_change_post[2]:1s), ETC: 5m 42s
Traceback (most recent call last):
  File "C:\Users\<USERNAMEREDACTED>\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VSEQF-4_0_1\__init__.py", line 747, in frame_step
    vu_meter.vu_meter_calculate(scene)
  File "C:\Users\<USERNAMEREDACTED>\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VSEQF-4_0_1\vu_meter.py", line 84, in vu_meter_calculate
    for area in bpy.context.screen.areas:
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'areas'

**Comment by snuq** [comment]
huh. thats kindof what that function was supposed to be doing, the error is actually triggered when its checking to see if a sequence editor is visible.  im not sure how there could ever not be a screen object at all, but apparently its possible! i updated the code to check for a screen existing, and moved that code before it calculates the vu meter so it wont waste time calculating the meter when a sequencer is not open.
