### ISSUE TITLE
VSEQF Doesn't appear in Addon list after installation (Blender 2.81)

### ISSUE THREAD

**Issue by Raikudo** [snuq/VSEQF#5]
Hello Snug. Thanks for taking the effort to update the quick function addon for blender 2.8. I been using 2.79 for Blender 2.79 for quite along time and its working great

I decided to venture into blender 2.8 (2.81 the current as of the writing of this post). I followed the same old procedure to add addons. For some reason after the installation the addon doesn't show up in preference >> Addons list.

I had no problems installing other third party addons such as VSE_Transform_Tool in the new blender Evee

I did go through the read me file for VSEQF 2.81. in case I could have missed something, also updated to 2.81a in case it will help, no luck so far

Further information that might help

I have both blender 2.79 and 2.81a installed side by sid

With 2.79 installed from windows 64 setup version and 2.81a installed as portable unzipped into a separate folder

Intend to remove 2.79 once I completely get used to the new one, different workflow, some older addons compatibility issues plus being in the middle of developing blender course based on 2.79. so don't want to through away the old version just yet

Anyway mentioning this in case multiple blender versions could be causing potential conflict

Best Regards
Ahmed Anis

**Comment by snuq** [comment]
Ouch, sorry about that, looks like Blender has an undocumented... ah, 'feature'...  where addon folders cannot have a period in the name.  So, when I named the branch '2.81' and Github made the addon folder 'VSEQF-2.81', Blender could not detect it. 
I have renamed all the branches to not have periods in them, it should install properly if you download the newest version.

**Comment by Raikudo** [comment]
Sounds similar to coding where certain characters are not allowed otherwise it will result in compile or script error. I recall having to deal with certain file naming restriction that would result in mysterious exception error during one of my OpenGL 3d project in university which took a lot of research to figure out what was going on

Anyway I have re downloaded your modified version and I can see it now in the list. 

Thanks for help Snug

Sincerely
Ahmed Anis
