### ISSUE TITLE
Ripple delete audio > Crash

### ISSUE THREAD

**Issue by tin2tin** [snuq/VSEQF#9]
I cut an audio strip in 3 pieces and move the rightmost strip a bit away.
Then I select the middle strip and hit Ctrl + K to open the Cut menu and select ripple delete. 
Blender crashes.

**Comment by snuq** [comment]
hmm, cant confirm, can you provide a .blend file where it crashes?  What blender version are you using?

**Comment by tin2tin** [comment]
Another one I can't reproduce now. Should have saved that old project. Sorry.

**Comment by snuq** [comment]
ah, could be a bug introduced in 2.82 also, I only run the current release pretty much
